- nebula_common/include/nebula_common/point_types.hpp
- nebula_common/src/nebula_common.cpp
- Improvement
https://tier4.atlassian.net/browse/RT1-2587
Modifies the point types with Autoware to ensure compatibility with existing algorithms downstream of the point cloud processing pipeline.
Verify the azimuth and timestamp fields in the point cloud published in `/aw_points_ex` are double-typed.
> feat(nebula): autoware double type

- README.md
- Improvement
Update parameter explanation for cloud angle settings
> docs: update README to reflect cloud angle settings correctly

- nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_hesai/hesai_hw_interface.hpp
- nebula_hw_interfaces/src/nebula_hesai_hw_interfaces/hesai_hw_interface.cpp
- Bug Fix
Minor spellcheck fix.
> chore(hesai_hw_interface): fix spelling errors

- nebula_messages/pandar_msgs/package.xml
- Bug Fix
Fixes a typo (Heisai vs Hesai)
> fix(pandar_msgs): fix typo

- nebula_messages/pandar_msgs/package.xml
- nebula_messages/velodyne_msgs/package.xml
- Bug Fix
`ament_cmake_auto` is used in `CMakeLists.txt`, but not declared as a dependency in `package.xml`
> build: add ament_cmake_auto dependency

- nebula_messages/velodyne_msgs/package.xml
- Bug Fix
https://github.com/tier4/nebula/issues/71
The XML version on this file has a typo, it should be 1.0 instead of 3.0
Confirm correct change
- [x ] Assign PR to reviewer
> fix(velodyne_msgs): change xml version 3.0 to 1.0

- nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/hesai_decoder.hpp
- nebula_ros/src/hesai/hesai_decoder_ros_wrapper.cpp
Signed-off-by: Yukihiro Saito <yukky.saito@gmail.com>
- New Feature
The XT-32 has been tested and confirmed to work on the actual device.
> feat: add range parameter for hesai

- build_depends.repos
> chore: multicast branch

- nebula_messages/continental_msgs/package.xml
- Bug Fix
`ament_cmake_auto` is use in `CMakeLists.txt` but not declared as a dependency in `package.xml`
Add `ament_cmake_auto` to `package.xml`
> build(continental_msgs): fix dependencies

- nebula_messages/nebula_msgs/package.xml
- Bug Fix
https://github.com/autowarefoundation/autoware-deb-packages/actions/runs/8892602199/job/24417095611?pr=85
This PR adds a build dependency for `ament_cmake_auto`, it's being used in `CMakeLists.txt` but not declared in `package.xml`
> build(nebula_msgs): fix dependencies

- nebula_sensor_driver/package.xml
> fix(nebula_sensor_driver): remove duplicated dependency

- .github/workflows/documentation.yml
I messed up #223. Here's to this one working.
> fix(docs): install requirements CORRECTLY in CI

- nebula_common/include/nebula_common/hesai/hesai_common.hpp
- nebula_ros/config/lidar/hesai/Pandar128E4X.param.yaml
See #294. Forgot to push the config default and the config print for hires mode :bow:
> chore(hires_mode): amend #294 - add forgotten-to-commit config option and config print

- nebula_ros/include/nebula_ros/common/diagnostics/rate_bound_status.hpp
- Improvement
- https://github.com/tier4/ros2_v4l2_camera/pull/29
See https://github.com/tier4/ros2_v4l2_camera/pull/29 for details.
> chore(nebula_ros): add topic rate bound status header

- nebula_ros/include/nebula_ros/common/diagnostics/liveness_monitor.hpp
- nebula_ros/include/nebula_ros/common/diagnostics/severity_latch.hpp
- nebula_ros/include/nebula_ros/hesai/diagnostics/packet_loss_diagnostic.hpp
- Bug Fix
- #324 -- introduced a thread synchronization bug
- #325 -- introduced another one
The two above PRs introduced thread synchronization bugs: the `tick()`, `on_lost()` and `submit()` member functions of the `LivenessMonitor`, `PacketLossDiagnosticTask` and `SeverityLatch` respectively collided with the `run()` function.
The former two functions are running in the UDP decoder thread while the latter is running on a ROS2 executor thread.
While any buggy behavior could not be produced on both of my machines, and during review, this issue slipped through the cracks. When testing on the bus reference vehicle HIL bench, I was able to observe crashes, and compiling and running with AddressSanitizer yielded:
```c++
AddressSanitizer: heap-use-after-free
WRITE of size 25 at 0x603000a70830 …
```
> fix(hesai): proper thread synchronization in diag-related modules

- .cspell.json
- nebula_ros/CMakeLists.txt
- nebula_ros/include/nebula_ros/common/single_consumer_processor.hpp
- nebula_ros/include/nebula_ros/hesai/decoder_wrapper.hpp
- nebula_ros/src/hesai/decoder_wrapper.cpp
- nebula_ros/test/test_single_consumer_processor.cpp
- Improvement
- [TIER IV INTERNAL](https://star4.slack.com/archives/C057JDFS5M2/p1749122012441849) -- internal discussion
- [@ohsawa1204's proof of concept](https://github.com/ohsawa1204/nebula/tree/perf-packet_drop)
Nebula recently had optimizations made to allow for zero-copy publishing of pointclouds (#335). Thus, no matter whether it is launched in a component container or standalone, pointcloud publishing is near-instant. However, the `/pandar_packets` topic used exclusively or recording is not able to benefit from the same optimiations, as tools like `ros2 bag record` do not have support for Agnocast. Also, recording over the network can not be implemented in a zero-copy manner.
The packet topic was thus continuing to block the decoding thread, which lead to packet loss for the …
> perf(hesai): publish packets in separate thread

- nebula_common/include/nebula_common/continental/continental_ars548.hpp
- nebula_decoders/src/nebula_decoders_continental/decoders/continental_ars548_decoder.cpp
- nebula_ros/src/continental/continental_ars548_decoder_wrapper.cpp
- New Feature
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C076E8EBJTG/p1753931985252599)
Add selected sensor configuration to diagnostics array.
[Screencast from 07-31-2025 04:24:00 PM.webm](https://github.com/user-attachments/assets/0f28288f-2816-4c68-bb4d-520be2a2418e)
> feat(continental_ars548): add sensor configuration to diagnostics

- nebula_ros/src/continental/continental_ars548_hw_interface_wrapper.cpp
- nebula_ros/src/continental/continental_srr520_hw_interface_wrapper.cpp
- Chore: tf2_ros to hpp headers
Automated regex replace
Check compilation
> chore: tf2_ros to hpp headers

- .cspell.json
- nebula_ros/CMakeLists.txt
- nebula_ros/include/nebula_ros/common/single_consumer_processor.hpp
- nebula_ros/include/nebula_ros/hesai/decoder_wrapper.hpp
- nebula_ros/src/hesai/decoder_wrapper.cpp
- nebula_ros/test/test_single_consumer_processor.cpp
- Improvement
* backport of https://github.com/tier4/nebula/pull/343
> [!NOTE]
> My team is using `v0.2.4.x` , so I would like to backport [the performance improvements](https://github.com/tier4/nebula/pull/343) from the latest version.
> Nebula recently had optimizations made to allow for zero-copy publishing of pointclouds (#335). Thus, no matter whether it is launched in a component container or standalone, pointcloud publishing is near-instant. However, the /pandar_packets topic used exclusively or recording is not able to benefit from the same optimiations, as tools like ros2 bag record do not have support for Agnocast. Also, recording over the network can not be implemented in a zero-copy manner.
> 
> The packet topic was thus continuing to block the decoding thread, which lead to …
> perf(hesai): cherry-pick : publish packets in separate thread #343

- nebula_common/include/nebula_common/continental/continental_ars548.hpp
- nebula_decoders/include/nebula_decoders/nebula_decoders_continental/decoders/continental_ars548_decoder.hpp
- nebula_decoders/src/nebula_decoders_continental/decoders/continental_ars548_decoder.cpp
- nebula_ros/src/continental/continental_ars548_decoder_wrapper.cpp
- nebula_ros/src/continental/continental_ars548_hw_interface_wrapper.cpp
- Improvement
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/CEV8XMJBV/p1758275439614179?thread_ts=1756443528.624719&cid=CEV8XMJBV)
Cherry pick https://github.com/tier4/nebula/pull/356 and https://github.com/tier4/nebula/pull/357.
> feat(continental_ars548): cherry-pick #356 and #357
