tier4/nebula

nebula_common/include/nebula_common/nebula_common.hpp
nebula_common/src/nebula_common.cpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/hesai_scan_decoder.hpp
nebula_ros/src/hesai/hesai_decoder_ros_wrapper.cpp
nebula_ros/src/velodyne/velodyne_decoder_ros_wrapper.cpp

- Improvement
https://tier4.atlassian.net/browse/RT1-2587
Convert to sexagesimal degrees to match autoware specification.
Convert point stamp to absolute time to match autoware specification.
Verify the point cloud for Autoware published in `/aw_points_ex`
1. Contains sexagesimal degrees in the `azimuth`
2. Contains absolute time stamp in the `time_stamp` field (only for Hesai).

feate(nebula): convert to sexagesimal degress and absolute time to match aw

---

nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/pandar_qt_128.hpp
nebula_decoders/src/nebula_decoders_hesai/decoders/pandar_128_e4x_decoder.cpp
nebula_decoders/src/nebula_decoders_hesai/decoders/pandar_40_decoder.cpp
nebula_decoders/src/nebula_decoders_hesai/decoders/pandar_64_decoder.cpp
nebula_decoders/src/nebula_decoders_hesai/decoders/pandar_at_decoder.cpp
nebula_decoders/src/nebula_decoders_hesai/decoders/pandar_qt_128_decoder.cpp
nebula_decoders/src/nebula_decoders_hesai/decoders/pandar_qt_64_decoder.cpp
nebula_decoders/src/nebula_decoders_hesai/decoders/pandar_xt_decoder.cpp
nebula_decoders/src/nebula_decoders_hesai/decoders/pandar_xtm_decoder.cpp
nebula_ros/src/hesai/hesai_decoder_ros_wrapper.cpp

- Bug Fix
https://tier4.atlassian.net/browse/RT1-935?atlOrigin=eyJpIjoiOWNkYWM0ZWQ1Mjg3NGM2MGI2NTExOWM5NDM2YTAxNjYiLCJwIjoiaiJ9
Updates the time_stamp time field calculation algorithm on all hesai decoders.

fix(nebula): relative stamp

---

README.md
nebula_ros/config/hesai/Pandar128E4X.yaml
nebula_ros/config/hesai/Pandar40P.yaml
nebula_ros/config/hesai/PandarQT64.yaml

- Improvement
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-2587)
Updates README to be consistent with current driver implementation.

docs: readme update

---

build_depends.repos
nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_common/nebula_hw_interface_base.hpp
nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_hesai/hesai_hw_interface.hpp
nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_velodyne/velodyne_hw_interface.hpp
nebula_hw_interfaces/package.xml
nebula_ros/include/nebula_ros/hesai/hesai_hw_interface_ros_wrapper.hpp
nebula_ros/include/nebula_ros/hesai/hesai_hw_monitor_ros_wrapper.hpp
nebula_ros/src/hesai/hesai_hw_monitor_ros_wrapper.cpp

- Improvement
https://tier4.atlassian.net/browse/RT1-3373?atlOrigin=eyJpIjoiODU3ZmM4ZjA4MGRhNGMzM2ExOTJjZGI3ZTM4MmYyYWMiLCJwIjoiaiJ9
Rename TCP/HTTP-enabled transport_drivers package to avoid conflicts with the existing transport_drivers package.
* Clone this branch
* Switch to the `boost` branch for `transport_drivers.`
* Compile Nebula
* Run tests
* Test Nebula decoders with actual sensor(s).

refactor: rename transport_drivers to boost_transport_driver

---

nebula_common/src/nebula_common.cpp
nebula_ros/src/velodyne/velodyne_decoder_ros_wrapper.cpp

- Bug Fix
[](https://star4.slack.com/archives/C057JDFS5M2/p1691462406694639?thread_ts=1691455050.384009&cid=C057JDFS5M2)
Fixes Autoware points point independent timestamp calculation.

fix: Update velodyne point stamp calculation

---

.cspell.json
.gitignore
README.md
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/pandar_at_decoder.hpp
nebula_decoders/src/nebula_decoders_hesai/decoders/pandar_at_decoder.cpp
nebula_ros/include/nebula_ros/hesai/hesai_decoder_ros_wrapper.hpp
nebula_ros/launch/nebula_launch.py
nebula_ros/src/hesai/hesai_decoder_ros_wrapper.cpp
scripts/plot_times.py
scripts/profiling_runner.bash
scripts/requirements.txt

- Improvement
--
This PR improves performance of the Hesai AT128 decoder by approx. 23% without changing the logical output.
To achieve this, three changes have been made:
* Decoding points directly to `scan_pc_` and `overflow_pc_` instead of temporary buffers and re-using the buffers (~ 11%point improvement)
* Removing unused copy operation for incoming scan packets (~ 9%point improvement)
* Combining azimuth and elevation sin/cos lookup tables as they were exact duplicates (~ 4%point improvement)
Points were decoded in `convert(block_id)` to a temporary PointCloud, the contents of which were then copied to `scan_pc_` or `overflow_pc_` respectively. This caused avoidable latency. Now, depending on whether the current block being decoded is in a new frame/scan or not, `convert(block_id, …

perf(nebula): optimize AT128 decoder performance

---

nebula_ros/config/velodyne/VLP32.yaml
nebula_ros/src/velodyne/velodyne_hw_monitor_ros_wrapper.cpp

- Bug Fix
Addresses issue #44 
Allows the minimum and maximum cloud angle parameters to be up to 360 degrees.
The hardware interface automatically converts a 360 degree value into 359 (previously implemented in #40).
Launch the hardware monitor with cloud_min_angle and cloud_max_angle at the limits (0 and 360 degrees).

fix(velodyne_hw_monitor): allow max cloud angle of 360 degrees

---

README.md

- Improvement
Minor changes to README to include more information on Nebula features in the introduction.

docs(README): update features of Nebula

---

nebula_ros/src/velodyne/velodyne_decoder_ros_wrapper.cpp

- Improvement
@mojomex created profiling scripts in this PR: https://github.com/tier4/nebula/pull/37
Thanks to @mojomex, it is easy to measure performance of the driver. However the necessary logging code wasn't added for Velodyne. I added the logging to `velodyne_decoder_ros_wrapper.cpp` so that it is possible to use existing scripts to mesure process time for also Velodyne lidars.
The only modification is on `velodyne_decoder_ros_wrapper.cpp`. I added logging code according to `hesai_decoder_ros_wrapper.cpp`.
After building the package, go to the `scripts` directory and run:
```bash
./profiling_runner.bash vlp16 -m VLP16 -b <your_bag_file_which_includes_/velodyne_packets>
./profiling_runner.bash vls128 -m VLS128 -b <your_bag_file_which_includes_/velodyne_packets>
python3 plot_times.py …
```

feat(velodyne_ros_wrapper): add profiling log to velodyne

---

nebula_examples/CMakeLists.txt
nebula_examples/include/hesai/hesai_ros_offline_extract_bag_pcd.hpp
nebula_examples/include/hesai/hesai_ros_offline_extract_pcd.hpp
nebula_examples/include/velodyne/velodyne_ros_offline_extract_bag_pcd.hpp
nebula_examples/package.xml
nebula_examples/src/hesai/hesai_ros_offline_extract_bag_pcd.cpp
nebula_examples/src/hesai/hesai_ros_offline_extract_bag_pcd_main.cpp
nebula_examples/src/hesai/hesai_ros_offline_extract_pcd.cpp
nebula_examples/src/hesai/hesai_ros_offline_extract_pcd_main.cpp
nebula_examples/src/velodyne/velodyne_ros_offline_extract_bag_pcd.cpp
nebula_examples/src/velodyne/velodyne_ros_offline_extract_bag_pcd_main.cpp

- Bug Fix
This PR fixes the lint errors and enables the linters in `package.xml`

fix(nebula_examples): fix lint errors. Add ament_lint dependencies

---

.github/workflows/build-and-test-differential.yaml

ci: workflows. disable clang-tidy

---

nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/hesai_packet.hpp

- Bug Fix
Hesai Decoder. Replace `std::mktime` with `timegm` to take into consideration non UTC times.
- Play a rosbag with `pandar_packets` msg
- Launch the hesai_decoder corresponding to the packets being played.
- Confirm the decoded timestamp matches the current Time Zone.

fix: hesai_decoder replace mktime with timegm

---

nebula_hw_interfaces/src/nebula_velodyne_hw_interfaces/velodyne_hw_interface.cpp
nebula_ros/src/velodyne/velodyne_hw_interface_ros_wrapper.cpp

- Bug Fix
Allows Velodyne sensors to use `sensor_setup:=False` regardless of the launch and sensor setup.
Fixes https://github.com/tier4/nebula/issues/53
Launch 
`ros2 launch nebula_ros velodyne_launch_all_hw.xml sensor_model:=SENSOR setup_sensor:=False`

fix(velodyne): allow setup_sensor False

---

nebula_tests/hesai/hesai_ros_decoder_test.hpp
nebula_tests/hesai/hesai_ros_decoder_test_main.cpp

- Improvement
This PR gets rid of the designated initializers in the `nebula_tests` package which caused compiler warnings as this feature is only supported from C++20 onward.
Also made tiny changes to other parts of the tests that raised warnings (unused parameters etc.). There are now no warnings at all when compiling the tests.
```
colcon build --packages-up-to nebula_tests
colcon test --event-handlers console_cohesion+ --packages-select nebula_tests
```

test(nebula_tests): remove designated initializers

---

nebula_common/CMakeLists.txt
nebula_decoders/CMakeLists.txt
nebula_examples/CMakeLists.txt
nebula_hw_interfaces/CMakeLists.txt
nebula_ros/CMakeLists.txt

- Bug Fix
Closes:
- https://github.com/tier4/nebula/issues/95
See the issue.
Here are the warnings from the nebula repo CI without this PR:
- https://github.com/tier4/nebula/actions/runs/6887317522/job/18734317419#step:7:3901
You can check the CI build logs and see if the warnings are gone.
- https://github.com/tier4/nebula/actions/runs/6888656166/job/18738066582?pr=96#step:6:3935
Also the total lines in the build output went from 6438 -> 5440, 1000 line reduction.

build: mark PCL and YAML_CPP as SYSTEM

---

nebula_common/CMakeLists.txt
nebula_decoders/CMakeLists.txt
nebula_examples/CMakeLists.txt
nebula_hw_interfaces/CMakeLists.txt
nebula_messages/pandar_msgs/CMakeLists.txt
nebula_ros/CMakeLists.txt
nebula_sensor_driver/CMakeLists.txt
nebula_tests/CMakeLists.txt

- Bug Fix
The CMake version specified by most launchfiles results in a build warning, because of undefined `cmake_policy` for find_package` behaviour. This PR requests a newer version and unifies all CMakeLists.txt throughout the project.
Simple clean build! Previously, this warning would appear multiple times:
>CMake Warning (dev) at CMakeLists.txt:6 (find_package):
> Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
> Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
> command to set the policy and suppress this warning.
>
> CMake variable PCL_ROOT is set to:
>
>  /usr
>
> For compatibility, CMake is ignoring the variable.
>This warning is for project developers.  Use -Wno-dev to suppress it.`
This warning should now be gone.
**PR …

chore: update cmake versions to remove build warning

---

.cspell.json

- Spellcheck
Adds "DHAVE" to the spellcheck exceptions to avoid CI/CD errors (spell-check-differential).
Check that CI/CD passes.

chore: add DHAVE to ignore list

---

nebula_hw_interfaces/src/nebula_hesai_hw_interfaces/hesai_hw_interface.cpp

`NebulaModelToHesaiModelNo` was explicitly handling Velodyne models, while it should really just handle everything that is `not Hesai` the same. Because of this, PR #77 and future sensor additions cause warnings in this piece of code (enum value XYZ not handled).
- Improvement
The function on question now has a generic `default` case for any non-Hesai sensors. Functionally it is exactly the same as before.
Confirm there are no build warnings like "Enum value XYZW not handled in switch statement", confirm in the diff that the code is equivalent.
- **Build and test for PR**: Required to pass …

refactor(hesai_hw_interface): remove mention of Velodyne sensors in Hesai code

---

nebula_hw_interfaces/src/nebula_hesai_hw_interfaces/hesai_hw_interface.cpp
nebula_hw_interfaces/src/nebula_velodyne_hw_interfaces/velodyne_hw_interface.cpp

- Bug Fix
None.
```cpp
// old
packet.stamp.nanosec = static_cast<int>((now_nanosecs / 1000000000. - static_cast<double>(now_secs)) * 1000000000);
// new
packet.stamp.nanosec = static_cast<std::uint32_t>(now_nanosecs % 1000000000);
```
The first line of code you provided appears to have a bug related to the calculation of the nanoseconds portion of a timestamp. Here's the breakdown:
1. **First Line Analysis:**
- `packet.stamp.nanosec = static_cast<int>((now_nanosecs / 1000000000. - static_cast<double>(now_secs)) * 1000000000);`
- This line seems to be trying to calculate the nanoseconds part by taking the total nanoseconds (`now_nanosecs`), dividing it by 1 billion (to get the seconds part), and then subtracting the seconds part (`now_secs`) from it. This result is then multiplied by 1 …

fix(hw_interfaces): fix the lossy nanoseconds extraction

---

nebula_ros/src/velodyne/velodyne_decoder_ros_wrapper.cpp

- Bug Fix
None.
Entire Velodyne scan was copied into an unused variable. This PR removes the variable.
Hopefully the compiler already optimizes this out but just to be sure, it's better to remove it.
- Check if it compiles
- Check if variable is really unused?

fix(velodyne): remove unused large variable/copy

---

nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_velodyne/velodyne_hw_interface.hpp
nebula_hw_interfaces/src/nebula_velodyne_hw_interfaces/velodyne_hw_interface.cpp

- Bug Fix
This PR fixes the `unused parameter ‘sensor_configuration’` warning when building `nebula_hw_interfaces`.
The parameter was unused because it was of type `SensorConfigurationBase` while the function in question needed `VelodyneSensorConfiguration` and used the member variable of the correct type, ignoring the parameter.
The member now gets updated with the casted parameter value.

fix: get rid of "unused parameter ‘sensor_configuration’" warning for Velodyne

---

.cspell.json
nebula_decoders/include/nebula_decoders/nebula_decoders_robosense/decoders/bpearl_v3.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_robosense/decoders/bpearl_v4.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_robosense/decoders/helios.hpp

- Bug Fix
Currently, to get the time synchronization status, wrong field is used. If the sensor doesn't have time synchronization, driver doesn't start.
The current checked field is `time_sync_mode` states the mode that was set on web interface such as GPS or PTP.
This PR fixes this issue by checking `sync_status` field which is the correct way to see time synchronization status.
You can use pcap files to test: https://github.com/tier4/nebula/pull/77#issuecomment-1831496822

fix(robosense): use correct field to check time sync status

---

nebula_decoders/include/nebula_decoders/nebula_decoders_velodyne/decoders/velodyne_scan_decoder.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_velodyne/decoders/vlp16_decoder.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_velodyne/decoders/vlp32_decoder.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_velodyne/decoders/vls128_decoder.hpp
nebula_decoders/src/nebula_decoders_velodyne/decoders/vlp16_decoder.cpp
nebula_decoders/src/nebula_decoders_velodyne/decoders/vlp32_decoder.cpp
nebula_decoders/src/nebula_decoders_velodyne/decoders/vls128_decoder.cpp
nebula_decoders/src/nebula_decoders_velodyne/velodyne_driver.cpp

The timestamps in the vls128 were still relative to the last pointcloud, which was producing some errors Additionally, when entire scans were dropped, the overflow was not being handled correctly (this bug was also present in the awf velodyne driver)
- Bug Fix
[TIER IV INTERNAL LINK (discussion)](https://star4.slack.com/archives/C057JDFS5M2/p1703655034662449)
[TIER IV INTERNAL LINK (footage)](https://drive.google.com/drive/folders/1sB3iTCVo9Z4ysu-HwtBLWnPHRN3Vmk6_?usp=drive_link)
2 bugs were discovered and addressed related to the handling of time stamps during pointcloud overflow between scans.
Context: 
- The lidar scan has an azimuth value (the origin is defined by the sensor) and usually a pointcloud would start at 0 degrees and end in 360 degrees. 
- However, to synchronize multiple …

fix(velodyne_decoder): overflow handling in vls128

---

nebula_decoders/include/nebula_decoders/nebula_decoders_velodyne/decoders/vlp16_decoder.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_velodyne/decoders/vlp32_decoder.hpp
nebula_decoders/src/nebula_decoders_velodyne/decoders/vlp16_decoder.cpp
nebula_decoders/src/nebula_decoders_velodyne/decoders/vlp32_decoder.cpp
nebula_decoders/src/nebula_decoders_velodyne/decoders/vls128_decoder.cpp

- Bug Fix
https://github.com/tier4/nebula/pull/111
This PR extends the changes in https://github.com/tier4/nebula/pull/111. See **Nebula-only problem** in that PR description for a detailed overview of the problem.
Code review (currently do not have rosbags that can reproduce this issue).

fix(velodyne_decoder): vlp16 and vlp32 overflow handling

---

nebula_decoders/CMakeLists.txt
nebula_decoders/include/nebula_decoders/nebula_decoders_velodyne/decoders/velodyne_scan_decoder.hpp
nebula_decoders/src/nebula_decoders_velodyne/decoders/vlp16_decoder.cpp
nebula_decoders/src/nebula_decoders_velodyne/decoders/vlp32_decoder.cpp
nebula_decoders/src/nebula_decoders_velodyne/decoders/vls128_decoder.cpp

- Improvement
before this PR, `angles/angles.h` is included in a public header file of `velodyne_scan_decoder.hpp`, so that any project that uses this repo needs to include `angles` as well.
After this PR, `angles/angles.h` is moved to .cpp files, so it's internal to this repo. Other project that uses this repo does not need to find and include `angles`.
This can reduce compile time for both colcon/cmake and gcc.
Another minor change is the 
```
#if defined(ROS_DISTRO_FOXY) || defined(ROS_DISTRO_GALACTIC)
#include <angles/angles.h>  //Galactic
#else
#include <angles/angles/angles.h>  //Humble
#endif
```
which is not necessary if `angles` is installed according to https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L403
Many other ros2 projects are not using `#if/#endif` …

build: make #include <angles/angles.h> internal to cpp file

---

nebula_ros/launch/robosense_launch.all_hw.xml

- Bug Fix
Fixes: https://github.com/tier4/nebula/issues/115
Since Robosense lidars provides calibration data via DIFOP packets, we don't require a calibration file. Every time the driver is started, calibration data is parsed from incoming DIFOP packets.
The calibration file argument was added during development process and removed after further developments. Currently, Robosense driver doesn't use them.
The Robosense launch file should make the driver launch without errors.

fix(nebula_ros): remove calibration file argument from robosense launch

---

nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/hesai_decoder.hpp
nebula_ros/src/hesai/hesai_decoder_ros_wrapper.cpp
nebula_tests/hesai/hesai_ros_decoder_test.cpp
nebula_tests/hesai/hesai_ros_decoder_test.hpp
nebula_tests/hesai/hesai_ros_decoder_test.yaml
nebula_tests/hesai/hesai_ros_decoder_test_main.cpp

- New Feature
The XT-32 has been tested and confirmed to work on the actual device.

feat: range param for hesai

---

nebula_common/include/nebula_common/hesai/hesai_common.hpp
nebula_common/include/nebula_common/nebula_common.hpp
nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_hesai/hesai_hw_interface.hpp
nebula_hw_interfaces/src/nebula_hesai_hw_interfaces/hesai_hw_interface.cpp
nebula_ros/launch/hesai_launch_all_hw.xml
nebula_ros/launch/hesai_launch_component.launch.xml
nebula_ros/launch/nebula_launch.py
nebula_ros/src/hesai/hesai_hw_interface_ros_wrapper.cpp

- New Feature
Hesai OT128 has different handling of PTP settings, as it only allows 802.1AS Automotive and allows setting of switch type (TSN or not). This in turn changes PTP from the default P2P to use E2E when the switch type is changed to non-TSN.
- Connect OT128 sensor
- Configure sensor with 802.1AS Automotive via launchfile, and set `ptp_switch_type` to `TSN` or `NON_TSN`
- Confirm PTP operation, and also check that the delay measurement mechanism is correctly configured
ToDo:

feat(hesai): add TSN settings for Hesai sensors (OT128) 

---

nebula_ros/launch/nebula_launch.py

- Bug Fix
When AT128 packets are played from `ros2 bag` and nebula is launched via `ros2 launch nebula_ros nebula_launch.py sensor_model:=PandarAT128 launch_hw:=False` without having been connected to a sensor before, pointclouds will not be output with the following error:
```
[component_container-1] [ERROR 1711437207.368933061] [HesaiDriver]: Scanned 624 packets, but no pointclouds were generated. Last azimuth: 959294 (ConvertScanToPointcloud() at /home/maxschmeller/nebula/src/nebula_decoders/src/nebula_decoders_hesai/hesai_driver.cpp:96)
[component_container-1] [WARN 1711437207.368961276] [hesai_driver_ros_wrapper_node]: Empty cloud parsed. (ReceiveScanMsgCallback() at /home/maxschmeller/nebula/src/nebula_ros/src/hesai/hesai_decoder_ros_wrapper.cpp:68)
```
Launching via the …

fix(nebula_launch): pass correct default path for AT128 correction file

---

nebula_common/include/nebula_common/velodyne/velodyne_calibration_decoder.hpp
nebula_common/src/velodyne/velodyne_calibration_decoder.cpp
nebula_decoders/src/nebula_decoders_velodyne/velodyne_driver.cpp
nebula_ros/src/velodyne/velodyne_decoder_ros_wrapper.cpp

- Improvement
More details in this [autoware issue](https://github.com/autowarefoundation/autoware.universe/issues/5539) and this [nebula issue](https://github.com/tier4/nebula/issues/122).
This PR is one of a group of PRs that aim to fix the Autoware logging system to reduce excessive error and warning logs on Autoware launch only on the Velodyne decoder.
Part of:
- https://github.com/autowarefoundation/autoware.universe/issues/5539
- Planning Simulation
- Run [Autoware planning simulator](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/), and you can see no more excessive and recurring errors, warnings, and info messages when the system running as expected
- Rosbag Replay Simulation
- Run [Autoware rosbag repay …

fix(log-messages): reduce excessive log messages in velodyne decoder

---

nebula_ros/include/nebula_ros/hesai/hesai_hw_monitor_ros_wrapper.hpp
nebula_ros/launch/hesai_launch_all_hw.xml
nebula_ros/launch/hesai_launch_component.launch.xml
nebula_ros/src/hesai/hesai_hw_monitor_ros_wrapper.cpp

- Bug Fix
* #126 -- last attempted fix
* [TIER IV INTERNAL LINK](https://tier4.atlassian.net/wiki/x/JwRxtQ) -- detailed troubleshooting
This PR fixes the OT128's 2s UDP packet drop issue (again, this time for node containers).
The culprit was a race condition between the HW monitor's `OnHesaiStatusTimer()` and `OnHesaiLidarMonitorTimer()` callbacks, which both access the non-thread-safe HW interface.
(Thread-safety will _probably_ be fixed by #131 as the `SendReceive()` function should be thread-safe there, as a side-effect of the other fixes made.)
Due to the race condition, the callbacks got into a deadlock, causing all TCP communication from HW monitor to stop. HW monitor is the only source of constant TCP traffic to the sensor (once per `diag_span`, default 1s) and is thought to …

fix(hesai_hw_monitor): fix 2s drops issue - again

---

nebula_common/include/nebula_common/util/expected.hpp

- Bug Fix
Added `#include <string>` which was missing from the header

fix(expected.hpp): add missing string include

---

build_depends.repos

- Bug Fix (temporary)
An error in git submodule configuration causes the documentation deployment to fail.
This PR removes submodules and adds required repositories to the `build.repos` file.

fix: remove git submodules to prevent docs build error

---

nebula_common/include/nebula_common/continental/continental_ars548.hpp
nebula_common/include/nebula_common/point_types.hpp

- Improvement
- Bug Fix
* Fixes #157 
* For reference: [the same fix in PCL](https://github.com/PointCloudLibrary/pcl/pull/3237)
This PR moves the `EIGEN_ALIGN16` from behind point structs to after the `struct` keyword, remaining compatible with GCC while enabling compilation with Clang (and enabling usage of all the great Clang tools :tada:)
:warning: Note: Nebula still does not compile on the newest Clang version (18) due to a tricky error in `transport_drivers`. The newest version I have tested with is Clang 15.
The code should still compile on GCC, but now compiles on Clang as well.
- …

fix: make Nebula Clang-compatible

---

nebula_ros/include/nebula_ros/common/watchdog_timer.hpp

- Bug Fix
The callback was being called even though there were frequent updates to the watchdog.
Printing the stamps, the latest stamp was newer than now. Ros time is not steady and it seems ptp affecting the watchdog's time

fix: non steady clock and watchdog

---

nebula_common/CMakeLists.txt
nebula_common/package.xml
nebula_decoders/CMakeLists.txt
nebula_decoders/include/nebula_decoders/nebula_decoders_robosense/robosense_info_driver.hpp
nebula_decoders/package.xml
nebula_examples/CMakeLists.txt
nebula_examples/include/hesai/hesai_ros_offline_extract_bag_pcd.hpp
nebula_examples/include/hesai/hesai_ros_offline_extract_pcd.hpp
nebula_examples/include/velodyne/velodyne_ros_offline_extract_bag_pcd.hpp
nebula_examples/package.xml
nebula_examples/src/common/parameter_descriptors.cpp
nebula_hw_interfaces/CMakeLists.txt
nebula_hw_interfaces/package.xml
nebula_ros/CMakeLists.txt
nebula_ros/package.xml
nebula_tests/CMakeLists.txt
nebula_tests/continental/CMakeLists.txt
nebula_tests/continental/continental_ros_decoder_test_ars548.hpp
nebula_tests/hesai/CMakeLists.txt
nebula_tests/hesai/hesai_common.hpp
nebula_tests/hesai/hesai_ros_decoder_test.hpp
nebula_tests/package.xml
nebula_tests/velodyne/CMakeLists.txt
nebula_tests/velodyne/velodyne_ros_decoder_test_vlp16.hpp
nebula_tests/velodyne/velodyne_ros_decoder_test_vlp32.hpp
nebula_tests/velodyne/velodyne_ros_decoder_test_vls128.hpp

Work in progress
- Improvement

feat(cmake): make colcon build fast again

---

nebula_common/include/nebula_common/continental/continental_ars548.hpp
nebula_common/include/nebula_common/point_types.hpp
nebula_hw_interfaces/src/nebula_continental_hw_interfaces/continental_ars548_hw_interface.cpp
nebula_hw_interfaces/src/nebula_continental_hw_interfaces/multi_continental_ars548_hw_interface.cpp

- Improvement
- Bug Fix
Similar PR currently merged in `develop`:
* #160 
@veqcc wants to analyze Autoware and Nebula using Clang-tooling, this PR is to make this possible before the (possibly long-winded) merge of `develop`.
There were two declared, but undefined member functions in the ARS548 HW interfaces that were addressed in
* #124 
which wouldn't link after compiling with Clang, so I implemented them as printing an error to the console for now (non-breaking change and better than failing silently). @knzo25 please check that this temporary warning is okay.
- **Build and test for PR**: …

fix(clang): make build pass with Clang

---

README.md
docs/installation.md

- Improvement
When trying to install Nebula on Ubuntu 20.04 with manually built Humble, a lot of Boost compile errors were emitted for
`big_float32_buf_t` and `load_little_u16` etc. which are only supported for Boost 1.74.0 and later. Add this requirement to the readme file to avoid trouble in the future.

docs(readme): add boost version requirements

---

nebula_common/include/nebula_common/continental/continental_ars548.hpp
nebula_common/include/nebula_common/continental/continental_srr520.hpp
nebula_common/include/nebula_common/hesai/hesai_common.hpp
nebula_common/include/nebula_common/nebula_common.hpp
nebula_common/include/nebula_common/robosense/robosense_common.hpp
nebula_common/include/nebula_common/velodyne/velodyne_common.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/hesai_decoder.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_robosense/decoders/robosense_decoder.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_robosense/decoders/robosense_info_decoder.hpp
nebula_examples/src/hesai/hesai_ros_offline_extract_bag_pcd.cpp
nebula_examples/src/hesai/hesai_ros_offline_extract_pcd.cpp
nebula_examples/src/velodyne/velodyne_ros_offline_extract_bag_pcd.cpp
nebula_hw_interfaces/src/nebula_robosense_hw_interfaces/robosense_hw_interface.cpp
nebula_hw_interfaces/src/nebula_velodyne_hw_interfaces/velodyne_hw_interface.cpp
nebula_ros/src/continental/continental_ars548_ros_wrapper.cpp
nebula_ros/src/continental/continental_srr520_ros_wrapper.cpp
nebula_ros/src/hesai/hesai_ros_wrapper.cpp
nebula_ros/src/hesai/hw_monitor_wrapper.cpp
nebula_ros/src/robosense/robosense_ros_wrapper.cpp
nebula_ros/src/velodyne/hw_monitor_wrapper.cpp
nebula_ros/src/velodyne/velodyne_ros_wrapper.cpp
nebula_tests/continental/continental_ros_decoder_test_ars548.cpp
nebula_tests/continental/continental_ros_decoder_test_srr520.cpp
nebula_tests/hesai/hesai_ros_decoder_test.cpp
nebula_tests/velodyne/velodyne_ros_decoder_test_vlp16.cpp
nebula_tests/velodyne/velodyne_ros_decoder_test_vlp32.cpp
nebula_tests/velodyne/velodyne_ros_decoder_test_vls128.cpp

- Improvement
Sensor configurations were printed without any special formatting before, making it hard to quickly, at a glance, verify sensor settings.
This PR proposes printing configs in a prettier format. See the below table for comparisons.
| Before | After |
|--------|--------|
| ![Screenshot from 2024-06-27 16-57-20](https://github.com/tier4/nebula/assets/6088931/05442b2f-abfe-4caa-a96f-94d25f9213f8) | ![Screenshot from 2024-06-27 16-48-51](https://github.com/tier4/nebula/assets/6088931/3573fb1d-9f45-46c1-a05d-ae678dff2841) |
|  | ![Screenshot from 2024-06-27 16-49-26](https://github.com/tier4/nebula/assets/6088931/650f91b0-6a67-4e12-a4c2-c343d1eeb69a) |
| ![Screenshot from 2024-06-27 16-57-34](https://github.com/tier4/nebula/assets/6088931/ed77fed0-5441-464e-8a91-642f158ec355) | …

feat: pretty-print sensor configurations

---

nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/angle_corrector.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/angle_corrector_calibration_based.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/angle_corrector_correction_based.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/hesai_decoder.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/hesai_packet.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/hesai_scan_decoder.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/hesai_sensor.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/pandar_128e3x.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/pandar_128e4x.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/pandar_40.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/pandar_64.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/pandar_at128.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/pandar_qt128.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/pandar_qt64.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/pandar_xt32.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/pandar_xt32m.hpp

- Improvement
This PR implements some of the suggestions and fixes from clang-tidy, in order to reduce the errors and warnings shown in the IDE. Most of these are pure style fixes.
This PR targets only hesai decoders for now.
No elaborate review necessary.

chore(hesai_decoders): implement clang-tidy fixes (mostly style-related)

---

nebula_hw_interfaces/src/nebula_hesai_hw_interfaces/hesai_hw_interface.cpp
nebula_ros/src/hesai/hesai_hw_monitor_ros_wrapper.cpp

- Hotfix
- [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C076E8EBJTG/p1723108703362159) -- request for this fix
This is a hotfix for until develop is merged, to suppress error messages for unsupported hardware monitor commands on 40P and AT128.
Instead of printing these messages
```
{"Head":{"ErrorCode":"3","Message":"Error: not support yet"}}: cannot open file
```
Nebula will now suppress the error and fill the affected diagnostic fields with "not supported":
Code changed to achieve this:
* in `ParseJson()`, convert the JSON string to a stream (passing a string to the `load_json` function will treat the string as a file, not as JSON
* return a 0-initialized struct instead of segfaulting during parsing for cases where the sensor responds with an error
* introduce a special case …

fix(hesai_hw_monitor): reduce log spam for unsupported hardware commands on AT128 and 40P

---

nebula_ros/src/hesai/hesai_ros_wrapper.cpp

- Bug Fix
When setting parameters during runtime, e.g. with `ros2 param set`, the return mode parameter was parsed with the wrong function, resulting in most return modes not being accepted. this PR fixes this.
Confirm all supported return modes can be set during runtime.

fix(hesai): correctly handle return mode when updating parameters

---

nebula_common/include/nebula_common/hesai/hesai_common.hpp
nebula_common/include/nebula_common/util/string_conversions.hpp
nebula_ros/schema/Pandar40P.schema.json
nebula_ros/schema/Pandar64.schema.json
nebula_ros/schema/PandarAT128.schema.json
nebula_ros/schema/PandarQT64.schema.json

- Bug Fix
- [TIER IV INTERNAL LINK](https://docs.google.com/spreadsheets/d/1GaSDaL6O-hMxIWGMWtwJeydzdQRDIwBQNwOrlAob3Tw/edit?usp=sharing) -- table of supported return modes
The supported return modes for some Hesai sensors were not correct:
* AT128 does not support all return modes Nebula allowed
* XT32 supports more return modes than Nebula allowed
Return mode `Dual` is a relic from Velodyne's driver and is kept in Nebula for backwards-compatibility reasons. However, the internal representation has been updated to the more precise, sensor-specific return modes (`LastStrongest` or `LastFirst` depending on the sensor).
Use [nebula_evaluation](https://github.com/tier4/nebula_evaluation) to test return modes on these sensors.
**PR Author should check the checkboxes below when creating the …

fix(hesai): fix supported return modes for Hesai sensors

---

nebula_ros/launch/continental_launch_all_hw.xml
nebula_ros/launch/hesai_launch_all_hw.xml
nebula_ros/launch/robosense_launch_all_hw.xml
nebula_ros/launch/velodyne_launch_all_hw.xml

- Improvement
Add all supported sensor models as choices for their respective launch file's `sensor_model` argument. This makes ROS 2 check if the model is spelled correctly at launch time, thus improving usability.
Check if Nebula still launches, and if all sensor models are mentioned.

chore(nebula_ros/launch): supply choices for  `sensor_model` launch argument

---

nebula_ros/launch/nebula_launch.py

- Improvement
- Bug Fix
The `nebula_launch.py` file was long deprecated but also had incorrect/incomplete launch arguments for some vendors/sensors.
This PR re-writes this file such that it only explicitly handles the `sensor_model` argument, finds the corresponding vendor-specific launch file and hands off all remaining arguments to that file.
This way, backwards-compatibility is still ensured and future changes to vendor launch files will not necessitate updates to `nebula_launch.py`.
Support for containers is purpusefully dropped since the vendor launch files also do not support it anymore. This could be added back in in the future.
* Try launching `nebula_launch.py` with only `sensor_model` as an argument.
* Try launching with vendor-specific arguments
* Try launching with a custom …

fix(nebula_launch.py): make the generic launch file hand off to the correct vendor's launch file

---

nebula_ros/launch/continental_launch_all_hw.xml
nebula_ros/launch/hesai_launch_all_hw.xml
nebula_ros/launch/robosense_launch_all_hw.xml
nebula_ros/launch/velodyne_launch_all_hw.xml

- Improvement
Add the `launch_hw` argument to all vendors' launch files explicitly (instead of having ROS 2 Launch read it from the `config_file`) to enable the following workflow:
With the same config:
1. Connect to a real sensor and record data to a rosbag
2. Later, replay that rosbag with Nebula in offline mode (`launch_hw:=false`)
Try and launch each vendor, once with `launch_hw` being set to `true`, and once to `false`.
Nebula should try to connect to the sensor in one case, and print a message saying it's listening to recorded packets in the other.
- **Build and test for PR**: Required …

feat(nebula_ros): support `launch_hw` parameter in console again to make replaying rosbags easier

---

nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_hesai/hesai_cmd_response.hpp

- Bug Fix
Run `colcon build --symlink-install --event-handlers=console_cohesion+ --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo --packages-up-to nebula_sensor_driver` in latest autoware workspace.
```
--- stderr: nebula_hw_interfaces
In file included from /home/mfc/projects/autoware/src/sensor_component/external/nebula/nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_hesai/hesai_hw_interface.hpp:19,
from /home/mfc/projects/autoware/src/sensor_component/external/nebula/nebula_hw_interfaces/src/nebula_hesai_hw_interfaces/hesai_hw_interface.cpp:1:
/home/mfc/projects/autoware/src/sensor_component/external/nebula/nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_hesai/hesai_cmd_response.hpp: In function ‘std::ostream& nebula::operator<<(std::ostream&, …
```

fix(nebula_hw_interfaces): add missing iomanip header

---

.github/workflows/build-and-test-differential.yaml
.github/workflows/build-and-test.yaml

- Improvement
- [Codecov before](https://app.codecov.io/gh/tier4/nebula/commit/18af521fc3a3ab1ce9c17ec94c2a0a8633317de4)
- [Codecov after](https://app.codecov.io/github/tier4/nebula/commit/1b8105e8cd6c5d15ea1c61c7bf15ce98d5d4131f)
This PR removes the `build` and `nebula_examples` folders from code coverage statistics.
The `build` folder contains the code-generation results from `nebula_msgs` etc. and should not be included (also, it's 9000 lines :exploding_head:).
The `nebula_examples` folder is not part of the main functionality of the software and thus, coverage is not important.
With this PR, coverage goes from 10% to 28%:
:warning: **Dummy changes in all modules were necessary to trigger the coverage report, these have since been reverted.**
Compare coverage results from before and …

chore: exclude build and example folders from coverage

---

.codecov.yml
.github/workflows/build-and-test-differential.yaml
.github/workflows/build-and-test.yaml

- Improvement
Improves this PR:
- #199 
Create a .codecov.yml file as recommended in CodeCov's documentation and move the excluded directory settings there. This allows for more flexibility and hopefully once and for all excluded `nebula_examples` from coverage too.

chore: create .codecov.yml and move ignored directories there

---

nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/angle_corrector_correction_based.hpp

- Improvement
- #173 -- the base for this PR, needed because AT128 is broken before this PR
:warning: This has to be rebased onto develop after #173 is merged, and then be merged.
Only AT128 normalized its points' `elevation` field to [0, 2pi) while other sensors allowed negative `elevation` values. While the normalization is done on azimuth as well and thus, for consistency sake, would be nice on the elevation field, too, this causes visualizations to look ugly when coloring by `elevation`. 
Anyway, trigonometry functions won't care about this change as they are periodic, and given that all other sensors are not normalizing elevation, it is safe to assume this doesn't impact downstream modules.
| Old (normalized) | New (unnormalized) |
|-|-|
| …

fix(at128): allow negative values in points' `elevation` fields

---

nebula_hw_interfaces/src/nebula_continental_hw_interfaces/continental_ars548_hw_interface.cpp

- Bug Fix
It fixes the naming of an internal variable in the continental ars548 hardware interface code.
Check that all occurrences of the misnamed variable were properly replaced.

chore: fix typos in the SetVelocityVehicle function

---

README.md
docs/installation.md
nebula_sensor_driver/CMakeLists.txt

- Improvement
- #197 -- installation failed for a user due to unclear instructions in the readme
Simplify the readme/installation pages:
- remove the comment about the TCP-enabled transport drivers as they are installed automatically and are now prefixed by `boost_` and thus not conflicting with ROS' transport_drivers anymore
- remove the recommendation to create a `src` directory and instead recommend direct cloning
- creating a `src` directory is one extra step which is not necessary
- some IDEs/tools expect config files, e.g. .clang-tidy to be in the project root, not `src`
- update the link to our about page
**PR Author should check the checkboxes …

docs: simplify installation instructions

---

docs/parameters.md
nebula_ros/config/lidar/hesai/Pandar128E4X.param.yaml
nebula_ros/config/lidar/hesai/Pandar40P.param.yaml
nebula_ros/config/lidar/hesai/Pandar64.param.yaml
nebula_ros/config/lidar/hesai/PandarAT128.param.yaml
nebula_ros/config/lidar/hesai/PandarQT128.param.yaml
nebula_ros/config/lidar/hesai/PandarQT64.param.yaml
nebula_ros/config/lidar/hesai/PandarXT32.param.yaml
nebula_ros/config/lidar/hesai/PandarXT32M.param.yaml
nebula_ros/config/lidar/velodyne/VLP16.param.yaml
nebula_ros/config/lidar/velodyne/VLP32.param.yaml
nebula_ros/config/lidar/velodyne/VLS128.param.yaml
nebula_ros/include/nebula_ros/hesai/hw_interface_wrapper.hpp
nebula_ros/include/nebula_ros/velodyne/hw_interface_wrapper.hpp
nebula_ros/schema/Pandar128E4X.schema.json
nebula_ros/schema/Pandar40P.schema.json
nebula_ros/schema/Pandar64.schema.json
nebula_ros/schema/PandarAT128.schema.json
nebula_ros/schema/PandarQT128.schema.json
nebula_ros/schema/PandarQT64.schema.json
nebula_ros/schema/PandarXT32.schema.json
nebula_ros/schema/PandarXT32M.schema.json
nebula_ros/schema/VLP16.schema.json
nebula_ros/schema/VLP32.schema.json
nebula_ros/schema/VLS128.schema.json
nebula_ros/schema/sub/hardware.json
nebula_ros/src/hesai/hesai_ros_wrapper.cpp
nebula_ros/src/hesai/hw_interface_wrapper.cpp
nebula_ros/src/velodyne/hw_interface_wrapper.cpp
nebula_ros/src/velodyne/velodyne_ros_wrapper.cpp

- Improvement
https://github.com/tier4/nebula/issues/136
This PR introduces a new parameter to the `hesai_ros_wrapper` and `velodyne_ros_wrapper` nodes, allowing hardware to launch with communication to the sensor disabled. In this configuration, the driver operates in a "listen-only" mode, receiving packet data without sending commands.
This functionality is required for the [AWSIM](https://github.com/tier4/AWSIM) simulator, where the LiDAR simulation plugin supports publishing raw packets via UDP but doesn't handle communication from the driver.
Prior to nebula version `0.2.0`, there was a workaround for this behaviour (as outlined in the related issue). However, recent architectural changes have removed the ability to use that workaround (segmentation fault appears).
Code review + test …

feat: allow to launch hardware in listen mode

---

nebula_decoders/include/nebula_decoders/nebula_decoders_robosense/robosense_driver.hpp
nebula_ros/include/nebula_ros/robosense/robosense_ros_wrapper.hpp
nebula_ros/src/robosense/robosense_ros_wrapper.cpp

- Bug Fix
- #147 -- bug introduced here
Since Nebula v0.2.0, or more specifically, since PR #147, DIFOP ("info") packets are not recorded/replayed anymore by Nebula.
This made diagnosing https://github.com/orgs/autowarefoundation/discussions/5378 impossible since the sensor configuration was not recorded.
Tested with the Helios PCAP from [here](https://github.com/tier4/nebula/pull/77#issuecomment-1831496822).

fix(robosense): include DIFOP packets in record/replay functionality

---

docs/api_reference.md
mkdocs.yml

- Improvement
This PR should make it much user-friendlier to navigate through the API reference.
Run
```shell
python3 -m pip install -U $(curl -fsSL https://raw.githubusercontent.com/autowarefoundation/autoware-github-actions/main/deploy-docs/mkdocs-requirements.txt)
cd src
mkdocs serve
```
and confirm the API reference tab is working as expected.

docs: create API reference page, link class/namespace/... references in navigation

---

nebula_decoders/src/nebula_decoders_velodyne/decoders/vlp16_decoder.cpp
nebula_decoders/src/nebula_decoders_velodyne/decoders/vlp32_decoder.cpp
nebula_decoders/src/nebula_decoders_velodyne/decoders/vls128_decoder.cpp

- Bug Fix
- [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C076ZGRC15X/p1730449377715739?thread_ts=1729751812.548579&cid=C076ZGRC15X) -- conversation
- [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT0-33996?focusedCommentId=193350) -- JIRA comment
Velodyne decoders were resetting only the point buffer but not the width/height header fields, resulting in an invalid pointcloud output when no valid points have been received in a scan.
This PR uses the correct reset method to fix this problem.

fix(velodyne): reset pointcloud correctly, including width and height fields

---

nebula_ros/src/hesai/hw_monitor_wrapper.cpp

- Improvement
https://tier4.atlassian.net/browse/RT0-34026
Added namespace so that hessai_hw_monitor can diag each LiDAR
You can verify with a bench test that a diag is published containing the namespace of each LiDAR

feat(hesai): add node name to diag name of hesai hw_monitor

---

nebula_tests/velodyne/velodyne_ros_decoder_test_vlp16.cpp
nebula_tests/velodyne/velodyne_ros_decoder_test_vlp32.cpp
nebula_tests/velodyne/velodyne_ros_decoder_test_vls128.cpp

- Improvement
This is a fix based on clang-tidy `bugprone-incorrect-roundings` error.
```
/home/emb4/autoware/autoware/src/sensor_component/external/nebula/nebula_tests/velodyne/velodyne_ros_decoder_test_vlp16.cpp:185:44: error: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead [bugprone-incorrect-roundings,-warnings-as-errors]
sensor_configuration.cloud_min_angle = 100 * (2 * M_PI - min_angle) * 180 / M_PI + 0.5;
^
/home/emb4/autoware/autoware/src/sensor_component/external/nebula/nebula_tests/velodyne/velodyne_ros_decoder_test_vlp16.cpp:186:44: error: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead [bugprone-incorrect-roundings,-warnings-as-errors] …
```

fix(nebula_tests): fix bugprone-incorrect-roundings

---

.clang-tidy
docs/contribute.md

- Improvement
- Inspired by [comma.ai's openpilot](https://github.com/commaai/openpilot/blob/master/docs/CONTRIBUTING.md)
Add contribution guidelines to Nebula. This allows easier contributions from the community and provides a clear set of rules and expectations we can refer to.

docs: add contribution guidelines

---

.github/workflows/documentation.yml

- Improvement
- #195 -- caused CI to fail
MkDocs fails in CI because the plugin `macros` was not installed correctly. Turns out, `docs/requirements.txt` was not being installed in the CI workflow, so I added it here.

fix(docs): install mkdocs plugins in CI workflow

---

mkdocs.yml

- Improvement
Some valid C++ sequences, such as `{{{`, overlap with the Jinja2 syntax and cause MkDocs errors. This PR disables the `macros` MkDocs plugin for all `*_source.md` files.

chore(docs): disable markdown macro rendering for source file pages

---

nebula_common/include/nebula_common/loggers/console_logger.hpp
nebula_common/include/nebula_common/loggers/logger.hpp
nebula_ros/include/nebula_ros/common/rclcpp_logger.hpp

- Improvement
- #169 -- first introduced here
This PR adds an abstract `nebula::drivers::loggers::Logger` interface that provides the following functions:
* `debug(msg)`
* `info(msg)`
* `warn(msg)`
* `error(msg)`
* `child(name) -> std::shared_ptr<Logger>` which creates a child logger (names are concatenated with `.`)
A `NEBULA_LOG_STREAM(log_func, stream_args)` macro is also provided for convenience.
There are currently two implementations of this interface:
* `nebula::drivers::loggers::ConsoleLogger` (in `nebula_common`)
* `nebula::drivers::loggers::RclcppLogger` (in `nebula_ros`)
The motivation of this PR is to, in the long run, remove the dependency on RCLCPP from all Nebula packages except `nebula_ros`.
**Reviewers …

feat: add a logging interface, dependency injectable loggers

---

nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_hesai/hesai_hw_interface.hpp
nebula_hw_interfaces/src/nebula_hesai_hw_interfaces/hesai_hw_interface.cpp
nebula_ros/src/hesai/hw_interface_wrapper.cpp

- Improvement
- #233 -- based on this PR
:heavy_check_mark: #233 has been merged, this PR is ready for merging :heavy_check_mark: 
Use the new Nebula logger interface and pass in a concrete logger on instantiation. Output with the RCLCPP logger is identical, except for the tag having gotten longer. This can be changed if desired.
The direct RCLCPP dependency of the HW interface is thus removed :tada:
Before:
After: 

feat(hesai_hw_interface): use dependency-injected logger, get rid of RCLCPP dependency

---

nebula_ros/src/hesai/hw_monitor_wrapper.cpp

- Improvement
- [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C076E8EBJTG/p1732785800907929) -- internal discussion
With this PR, the diagnostics status for `hesai_ptp` is set to `WARN`, not `ERROR` when `ptp_status` is `tracking`. Hesai's user manuals state that tracking still counts as synchronized, so Nebula should not report it as an error.
Since tracking can be a symptom of non-perfect PTP setups, the warning comes with a status message `synchronized, degraded`.

chore(hesai): make `tracking` a `WARN`ing instead of an `ERROR`

---

nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_hesai/hesai_hw_interface.hpp
nebula_hw_interfaces/src/nebula_hesai_hw_interfaces/hesai_hw_interface.cpp
nebula_ros/src/hesai/hesai_ros_wrapper.cpp
nebula_ros/src/hesai/hw_interface_wrapper.cpp
nebula_ros/src/hesai/hw_monitor_wrapper.cpp

- Improvement
- #205 - Hesai HW interface was left out due to other in-flight PRs that would have been a pain to merge at the time
Fix the case style of all symbols in the Hesai hardware interface. This marks the completion of the work started in #205.

refactor(hesai_hw_interface): case style fixes

---

nebula_ros/src/hesai/hesai_ros_wrapper.cpp

- Improvement
- [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C076E8EBJTG/p1733099784725949) -- internal discussion
- #243 -- this feature would rid us of the need to manage calibration files completely
When Nebula runs without a live Hesai sensor, it will search for an already-downloaded calibration file. If that is not found, it will log a message which was previously at log level `ERROR`.
As quite a common workflow is to decode recorded packets on a different machine without this downloaded file, it is more reasonable to demote this to `WARN`.
After the warning is emitted, Nebula falls back to a sensor-specific, generic calibration file and continues operation.
With #243, calibration data could be recorded alongside `/pandar_packets` and replayed on any machine, making this …

fix(hesai_ros_wrapper): demote calibration fallback message to WARN

---

nebula_common/include/nebula_common/continental/continental_ars548.hpp
nebula_decoders/src/nebula_decoders_continental/decoders/continental_ars548_decoder.cpp
nebula_ros/src/continental/continental_ars548_decoder_wrapper.cpp
nebula_ros/src/continental/continental_ars548_hw_interface_wrapper.cpp

- Bug Fix
We were publishing objects for corner radars, which is not a supported feature (from the sensor).
This PR disables them and provides warnings when users attempt to use corner radars

feat(ars548): disable object output for corner radars

---

build_depends.repos

- Improvement
- [autoware.repos](https://github.com/autowarefoundation/autoware/blob/9c95a422999736f7c8594b3488a1b116c0d565ff/autoware.repos#L97-L105) -- the repositories used by Autoware
The personal forks of `transport_drivers` and `ros2_socketcan` were temporary measures, and the Autoware Foundation is now maintaining those forks.
This PR reflects this change in the `.repos` file.

chore(build_depends): update the forks of Nebula's dependencies to the Autoware Foundation ones

---

nebula_ros/config/lidar/hesai/Pandar128E4X.param.yaml
nebula_ros/config/lidar/hesai/Pandar40P.param.yaml
nebula_ros/config/lidar/hesai/Pandar64.param.yaml
nebula_ros/config/lidar/hesai/PandarAT128.param.yaml
nebula_ros/config/lidar/hesai/PandarQT128.param.yaml
nebula_ros/config/lidar/hesai/PandarQT64.param.yaml
nebula_ros/config/lidar/hesai/PandarXT32.param.yaml
nebula_ros/config/lidar/hesai/PandarXT32M.param.yaml

- Improvement
- #231 -- commit that disallowed broadcast IP as `host_ip`
Replace the the `host_ip` default config parameter with one that is not the broadcast address - broadcast is disallowed by Nebula since #231.

chore(hesai): replace broadcast `host_ip`

---

nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_hesai/hesai_hw_interface.hpp
nebula_hw_interfaces/src/nebula_hesai_hw_interfaces/hesai_hw_interface.cpp
nebula_ros/include/nebula_ros/hesai/hesai_ros_wrapper.hpp
nebula_ros/src/hesai/hesai_ros_wrapper.cpp

- Improvement
- #231 -- using the UDP socket from this PR
Use the new UDP socket introduced in #231 as a drop-in, ASIO-free, transport-driver-free replacement for the old UdpDriver in HesaiHwInterface.
Tested on the 2nd gen bus reference vehicle.

feat(hesai_hw_interface): use new UDP socket implementation

---

.pre-commit-config.yaml

- Improvement
- #174 -- upgraded to a new version of prettier, which complains when there are no files to process
Add the `--no-error-on-unmatched-pattern` option to prettier so an empty file list will not cause pre-commit to fail.

chore(pre-commit): fix pre-commit error when prettier has no files to process

---

nebula_ros/config/lidar/hesai/PandarXT16.param.yaml
nebula_ros/schema/PandarXT16.schema.json

- Bug Fix
- #239 -- introduced a new parameter that was not yet defined for XT16
- #256 -- replaced the now-disallowed broadcast IP with an example host IP address
Update parameter file and schema of XT16 to match the newest changes already merged for ther sensors.

fix(xt16): update default parameters and schema to comply with #239, #256

---

.cspell.json
nebula_ros/CMakeLists.txt
nebula_ros/package.xml
nebula_ros/test/smoke_test.py
nebula_tests/package.xml

- Improvement
Add smoke tests for all sensors: each smoke test launches Nebula with the sensor's default configuration and with `launch_hw:=false`.
These ensure (among other behaviors) that:
* Nebula is launchable in its default configuration
* the node shuts down cleanly, without segfaults or exceptions
In a later PR, `launch_hw:=true` should also be included, testing whether Nebula can be terminated when waiting for a connection.

test(nebula_ros): add smoke tests

---

nebula_ros/test/smoke_test.py

- Improvement
- #240 -- these turn out to be flaky in CI
#240 is flaky in CI but not on my local machine (works on my machine :clown_face:). This leads me to believe that it's a timing issue - Nebula might still be in its startup phase when it's interrupted by the test framework, resulting in a non-zero exit code.
This PR makes the test suite wait for the `Wrapper=OK` output before interrupting Nebula.
Hope and pray.

test(nebula_ros): fix flaky smoke test

---

nebula_ros/CMakeLists.txt

Improvement
This PR introduces a minimal delta needed to enable the installation of shared libraries corresponding to the composable node targets for the differet ros wrappers into `/opt/ros/<distro>/lib` instead of `/opt/ros/<distro>/x86_64-linux-gnu/`.
This installation path matters when the ROS wrappers for the lidar drivers are used as composable nodes, the relevant shared libraries are reported as unavailable. Here are some details:
I created a binary release of this package locally using bloom using the following steps:
(Do a source build of `nebula_ros` package following the instructions on README)
```
apt-get install -qqy python-bloom fakeroot dpkg-dev debhelper
cd nebula_ros
bloom-generate rosdebian
fakeroot debian/rules binary
```
The `lib<lidar_type>_ros_wrapper.so` files get …

chore(nebula_ros): specify library destination for install targets

---

nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_velodyne/velodyne_hw_interface.hpp
nebula_hw_interfaces/src/nebula_velodyne_hw_interfaces/velodyne_hw_interface.cpp
nebula_ros/src/velodyne/hw_monitor_wrapper.cpp

- Bug Fix
Bug found slack thread: 
https://star4.slack.com/archives/CEV8XMJBV/p1739142264251479?thread_ts=1739139390.099319&cid=CEV8XMJBV
Added error handling for HTTP GET/POST requests in VelodyneHwInterface to address system crashes caused by unhandled exceptions during HTTP communication.
The system would crash with "Interrupted system call" errors when exceptions occurred during HTTP requests to the Velodyne sensor:
```
1739140782.9432542 [component_container_mt-52] ^[[0m[INFO 1739140768.990953850] [rclcpp] signal_handler(): "signal_handler(signum=2)" at (/home/autoware/pilot-auto.xx1/src/rclcpp/rclcpp/src/rclcpp/signal_handler.cpp:L71)^[[0m
1739140782.9433613 [component_container_mt-52] terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>' …
```

fix(nebula_hw_interfaces): handling http get post request exception

---

nebula_common/CMakeLists.txt
nebula_common/include/nebula_common/util/rate_checker.hpp
nebula_common/include/nebula_common/util/ring_buffer.hpp
nebula_common/test/test_rate_checker.cpp

- Improvement
- #253 -- tests for this PR
Added unit tests for the `rate_checker` introduced in #253.
Also found that I missed in my review that there's an unprotected divide-by-zero in `ring_buffer`, made it throw a runtime error when called empty.

test(rate_checker): add unit tests

---

nebula_hw_interfaces/src/nebula_hesai_hw_interfaces/hesai_hw_interface.cpp

- Improvement
- [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C076E8EBJTG/p1738827319580859) -- inquiry
The new datasheets for the XT series also contain the `SET/GET_PTP_LOCK_OFFSET` command, enable it for those sensors.
Test whether there is a PTC error thrown when using XT32 on its newest firmware.

chore(hesai): enable PTP lock threshold setting for XT series sensors

---

codecov.yml

- Improvement
Current CI is failing because of codecov being too strict.

ci(codecov): configure automatic (relaxed) coverage threshold, split analyses into vendors

---

nebula_ros/config/radar/continental/ARS548.param.yaml

- Improvement
- [TIER IV INTERNAL](https://star4.slack.com/archives/C076E8EBJTG/p1740449556909039)
The factory default sensor IP ends in `.113` but Nebula's default was `.114`, which is confusing for users and doesn't make for a good out-of-the-box experience. Fixed in this PR.

chore(ars548): change config for default IP to match the factory default

---

nebula_ros/include/nebula_ros/velodyne/hw_monitor_wrapper.hpp
nebula_ros/src/velodyne/hw_monitor_wrapper.cpp

- Bug Fix
- [TIER IV INTERNAL](https://star4.slack.com/archives/C076E8EBJTG/p1739770915233339) -- the reported issue
The `/cgi/snapshot.hdl` endpoint of the sensor is not meant to be polled every second. Doing that causes the sensor to sometimes drop communication for a while (see the linked issue above).
This hotfix removes the timer polling `get_snapshot` and the related, now unused code.
As far as I can tell, marking diag info stale did not work reliably before (updates from `get_diag` and `get_status` were ignored, and will not work at all now.
All diag information will still be output as before.
Test with a real VLP16, VLP32 and VLS128 and compare before/after, especially with advanced diag enabled.
**Reviewers …

fix(velodyne): remove heavy get_snapshot from HW monitor

---

nebula_common/package.xml
nebula_decoders/package.xml
nebula_examples/package.xml
nebula_ros/package.xml

- Improvement
We try to keep our images small. We do not need `lib*-dev` dependencies in our runtime image.
`<depend>` also means `<exec_depend>`.
See if it compiles. It's not required runtime.

build: do not exec_depend on build_depends

---

nebula_ros/CMakeLists.txt
nebula_ros/include/nebula_ros/continental/continental_ars548_ros_wrapper.hpp
nebula_ros/src/continental/continental_ars548_ros_wrapper.cpp

- Improvement
- Bug fix
- #226 -- Hesai for reference
- #240 -- smoke tests for reference
Does what the title says.
Reasons for this change:
* The multithreaded queue is not needed (receive buffers in the network stack take care of arriving data while decoding).
* The decoder thread had no mechanism for gracefully stopping, thus causing an exception on exit
* The above excption caused our smoke tests to fail
* Compare to the linked Hesai reference PR #226
* Test with `launch_hw:=false` and a rosbag
* Test with `launch_hw:=true` and a real sensor or pcap
- **Build and test for PR**: Required to …

perf(ars548): remove mtqueue

---

nebula_ros/src/hesai/hesai_ros_wrapper.cpp

- Bug Fix
- #251 -- bug snuck in in this PR
Forgot a `!` when rearranging parameter parsing in `on_parameter_change`, causing the `set_parameter` service call to fail on every parameter except `return_mode`.

fix(hesai_ros_wrapper): fix a bug where setting any parameter except return_mode during runtime fails

---

nebula_ros/CMakeLists.txt
nebula_ros/include/nebula_ros/velodyne/velodyne_ros_wrapper.hpp
nebula_ros/src/velodyne/velodyne_ros_wrapper.cpp

- Improvement
- Bug fix
- #226 -- Hesai for reference
- #240 -- smoke tests for reference
Does what the title says.
Reasons for this change:
* The multithreaded queue is not needed (receive buffers in the network stack take care of arriving data while decoding).
* The decoder thread had no mechanism for gracefully stopping, thus causing an exception on exit
* The above excption caused our smoke tests to fail
* Compare to the linked Hesai reference PR #226
* Test with `launch_hw:=false` and a rosbag
* Test with `launch_hw:=true` and a real sensor or pcap
- **Build and test for PR**: Required to …

perf(velodyne): remove mtqueue

---

nebula_ros/CMakeLists.txt
nebula_ros/include/nebula_ros/continental/continental_srr520_ros_wrapper.hpp
nebula_ros/src/continental/continental_srr520_ros_wrapper.cpp

- Improvement
- Bug fix
- #226 -- Hesai for reference
- #240 -- smoke tests for reference
Does what the title says.
Reasons for this change:
* The multithreaded queue is not needed (receive buffers in the network stack take care of arriving data while decoding).
* The decoder thread had no mechanism for gracefully stopping, thus causing an exception on exit
* The above excption caused our smoke tests to fail
* Compare to the linked Hesai reference PR #226
* Test with `launch_hw:=false` and a rosbag
* Test with `launch_hw:=true` and a real sensor or pcap
- **Build and test for PR**: Required to …

perf(srr520): remove mtqueue

---

nebula_ros/CMakeLists.txt
nebula_ros/include/nebula_ros/robosense/robosense_ros_wrapper.hpp
nebula_ros/src/robosense/robosense_ros_wrapper.cpp
nebula_ros/test/smoke_test.py

- Improvement
- Bug fix
- #226 -- Hesai for reference
- #240 -- smoke tests for reference
Does what the title says.
Reasons for this change:
* The multithreaded queue is not needed (receive buffers in the network stack take care of arriving data while decoding).
* The decoder thread had no mechanism for gracefully stopping, thus causing an exception on exit
* The above excption caused our smoke tests to fail
* Compare to the linked Hesai reference PR #226
* Test with `launch_hw:=false` and a rosbag
* Test with `launch_hw:=true` and a real sensor or pcap
- **Build and test for PR**: Required to …

perf(robosense): remove mtqueue

---

nebula_ros/include/nebula_ros/velodyne/hw_monitor_wrapper.hpp
nebula_ros/src/velodyne/hw_monitor_wrapper.cpp

- Refactor
https://github.com/tier4/nebula/pull/279
Some private variables in the Velodyne hardware monitor class were not being used. 
Therefore, these variables have been removed.
Please verify that the `nebula_ros` package compiles successfully using the following command:
```bash
colcon build --packages-up-to nebula_ros
```

refactor(velodyne): remove unused private variables from HW monitor

---

nebula_decoders/include/nebula_decoders/nebula_decoders_common/point_filters/downsample_mask.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/hesai_decoder.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/hesai_sensor.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/pandar_128e4x.hpp
nebula_decoders/tests/point_filters/test_downsample_mask.cpp

- Improvement
- #251 -- introduced mask based pruning filter
:warning: The below use cases are **not** affected by the flickering issue (already working fine):
* masks converted from #182
* black-and-white masks
* OT128 in standard/non-high-resolution mode
* other sensors
While the mask based pruning filter introduced in #251 works well for all supported Hesai sensors, including OT128 in standard mode, OT128's high resolution mode employs a dithering pattern that interferes with the pruning filter's one.
This results in flicker and could degrade perception performance etc.
This PR extends the `DownsampleMaskFilter` by allowing sensors to specify a transform function for azimuth/channel coordinates passed to the dithering algorithm. This allows the developer to include knowledge about the …

fix(ot128): introduce anti-flicker downsample dithering pattern

---

nebula_ros/include/nebula_ros/continental/continental_ars548_hw_interface_wrapper.hpp
nebula_ros/src/continental/continental_ars548_hw_interface_wrapper.cpp

- Bug Fix
In the case where a UDP connection fails, subscribers to odometry where still being active, culminating in segfaults.
Now, when a UDP errors happens, odometry will not be subscribed.

fix(continental_ars548): handling better udp errors

---

mkdocs_macros.py

- Improvement
Markdown tables generated from parameter schemas were overflowing due to parameter defaults like `$(find-pkg-share nebula_decoders)/calibration/hesai/$(var sensor_model).csv` which don't have any word breaks.
While the parameters cannot really be changed/shortened, this PR introduces an improvement to the `json_to_markdown` macro which adds [HTML `<wbr>` (line break opportunity) tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) after all `/`es in default parameters. If a parameter value is short enough to fit, this does not have any effect. For longer paths like the one above, line breaks can be added by the browser at those `<wbr>` marks, causing the table to render correctly.
| Before | After |
|-|-|
| ![Screenshot from 2025-04-10 …

chore(docs): ensure word breaks in long paths/URLs so that tables don't overflow

---

nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_continental/continental_ars548_hw_interface.hpp
nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_continental/continental_srr520_hw_interface.hpp
nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_robosense/robosense_hw_interface.hpp
nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_velodyne/velodyne_hw_interface.hpp
nebula_hw_interfaces/src/nebula_continental_hw_interfaces/continental_ars548_hw_interface.cpp
nebula_hw_interfaces/src/nebula_continental_hw_interfaces/continental_srr520_hw_interface.cpp
nebula_hw_interfaces/src/nebula_hesai_hw_interfaces/hesai_hw_interface.cpp
nebula_hw_interfaces/src/nebula_robosense_hw_interfaces/robosense_hw_interface.cpp
nebula_hw_interfaces/src/nebula_velodyne_hw_interfaces/velodyne_hw_interface.cpp
nebula_ros/src/continental/continental_ars548_hw_interface_wrapper.cpp
nebula_ros/src/continental/continental_srr520_hw_interface_wrapper.cpp
nebula_ros/src/robosense/hw_interface_wrapper.cpp
nebula_ros/src/velodyne/hw_interface_wrapper.cpp

- Improvement
- #233 - introduction of the Nebula logger
- #232 - reference PR (Hesai) for this one
Replace all `RCLCPP_` and `std::cout`, `std::cerr` etc. usage by `logger->` calls for all remaining vendors. For Hesai, this has already been done in #232, but there were some print statements remaining.
Supersedes #301.
- code review (should be straight-forward), commits are split by sensor/vendor
- confirm using PCAP or sensor that logging works as expected

refactor(nebula_hw_interfaces): use nebula logger everywhere

---

nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_continental/continental_ars548_hw_interface.hpp
nebula_hw_interfaces/src/nebula_continental_hw_interfaces/continental_ars548_hw_interface.cpp

- Improvement
- #231 -- introduces the new UDP socket (receive-only)
- #272 -- provides the send functionality needed for this PR
Introduce the new UDP socket to the ARS548 hardware interface. This 
* allows for accurate ingress timestamping
* will allow us to phase out transport_drivers in the future (#267)
Test with a real sensor if all data is sent/received as expected.

feat(ars548): use new UDP socket

---

nebula_decoders/src/nebula_decoders_continental/decoders/continental_ars548_decoder.cpp

- Bug Fix
- #284 -- introduced by this PR
Fixed a compiler error because of a not yet renamed `ambiguity_flag` reference. It is now renamed to `raw_ambiguity_flag`.
Interesting how it passed CI, possibly CCache is configured too loosely? #270 

fix(ars548): rename now non-existent ambiguity_flag to raw_ambiguity flag

---

nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_velodyne/velodyne_hw_interface.hpp
nebula_hw_interfaces/src/nebula_velodyne_hw_interfaces/velodyne_hw_interface.cpp
nebula_ros/config/lidar/velodyne/VLP16.param.yaml
nebula_ros/config/lidar/velodyne/VLP32.param.yaml
nebula_ros/config/lidar/velodyne/VLS128.param.yaml
nebula_ros/include/nebula_ros/velodyne/velodyne_ros_wrapper.hpp
nebula_ros/src/velodyne/velodyne_ros_wrapper.cpp

- Improvement
- #231 -- using the UDP socket from this PR
- #235 -- equivalent PR for Hesai
Use the new UDP socket introduced in #231 as a drop-in, ASIO-free, transport-driver-free replacement for the old UdpDriver in HesaiHwInterface.

perf(velodyne): use new UDP socket implementation

---

nebula_ros/include/nebula_ros/continental/continental_srr520_hw_interface_wrapper.hpp
nebula_ros/package.xml

- Bug Fix
```
/opt/ros/rolling/include/message_filters/message_filters/synchronizer.h:18:2: warning: #warning This header is obsolete, please include message_filters/synchronizer.hpp instead [-Wcpp]
18 | #warning This header is obsolete, please include message_filters/synchronizer.hpp instead
|  ^~~~~~~
```
These headers are backported to humble so this works.

fix: deprecation of .h files in message_filters

---

nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_continental/continental_ars548_hw_interface.hpp
nebula_hw_interfaces/src/nebula_continental_hw_interfaces/continental_ars548_hw_interface.cpp

- Bug Fix
- https://github.com/tier4/nebula/pull/305
The Nebula node crashes with an `undefined symbol` error when calling the service for the ARS548, because it references a logging function that was previously removed.
The function was removed [here](https://github.com/tier4/nebula/pull/305/files#diff-2b1f0c47fbbb918494d49bb22ff03d5042a7e730a8f9600f80a183ce7afdd8c6L521-L547).
```
[continental_ars548_ros_wrapper_node-34] /home/autoware/autoware.proj/install/nebula_ros/lib/nebula_ros/continental_ars548_ros_wrapper_node: symbol lookup error: /home/autoware/autoware.proj/install/nebula_hw_interfaces/lib/libnebula_hw_interfaces_continental.so: undefined symbol: _ZN6nebula7drivers18continental_ars54828ContinentalARS548HwInterface10print_infoENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE …
```

fix: ars548: replace removed logger with nebula logger

---

nebula_hw_interfaces/include/nebula_hw_interfaces/nebula_hw_interfaces_hesai/hesai_cmd_response.hpp
nebula_ros/include/nebula_ros/hesai/hesai_ros_wrapper.hpp
nebula_ros/include/nebula_ros/hesai/hw_interface_wrapper.hpp
nebula_ros/include/nebula_ros/hesai/hw_monitor_wrapper.hpp
nebula_ros/src/hesai/hesai_ros_wrapper.cpp
nebula_ros/src/hesai/hw_interface_wrapper.cpp
nebula_ros/src/hesai/hw_monitor_wrapper.cpp

- Improvement
This PR moves the diagnostic_updater from hw_monitor to ros_wrapper for Hesai.
Since the updater will be used by various diagnostics not just in HW monitor, this change allows for clean implementation of those coming-soon diagnostics.
Other effects:
* The redundant force_update timer has been removed, as diagnostic_updater already has its own timer.
* A get_inventory has been sent to the sensor from 2 places before, this has been reduced to 1.
Confirmed working with a [dummy TCP connection](https://github.com/tier4/pcap_replay) and a real sensor. Publish rate is the same 1 Hz as before.
**PR Author should check the checkboxes below before …

refactor(hesai): centralized diagnostic_updater

---

.github/workflows/build-and-test-differential.yaml
.github/workflows/build-and-test.yaml

The upstream issue is cleared, removing the workaround:
https://github.com/docker-library/official-images/pull/19162#issuecomment-2936730894

chore: revert "fix(ci): temporary workaround for expired ROS signing key (#331)"

---

nebula_ros/include/nebula_ros/continental/continental_ars548_decoder_wrapper.hpp
nebula_ros/include/nebula_ros/hesai/decoder_wrapper.hpp
nebula_ros/src/continental/continental_ars548_decoder_wrapper.cpp
nebula_ros/src/hesai/decoder_wrapper.cpp

- Improvement
- #127 -- watchdog timer introduced here for Hesai sensors
- #151 -- watchdog timer introduced here for ARS548
- #326 -- rate bound status introduced here
- #322 -- rate bound status introduced here for Hesai sensors
- #327 -- rate bound status introduced here for ARS548
This PR removes the `WatchdogTimer` for pointcloud output (Hesai) and packet reception (ARS548) in favor of the already merged rate bound status diagnostics for pointcloud output (Hesai) and detection and object outputs (ARS548).
There have been multiple inquiries about the logging frequency and failure modes of `WatchdogTimer`, so we plan on sunsetting this feature starting with this PR.
* confirm that the new diagnostics are at least equivalent in diagnostic quality to `WatchdogTimer`
* confirm there is no …

chore(hesai,ars548): remove watchdog timer in favor of rate bound status

---

.cspell.json
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/decoders/functional_safety.hpp
nebula_decoders/include/nebula_decoders/nebula_decoders_hesai/hesai_driver.hpp
nebula_decoders/src/nebula_decoders_hesai/hesai_driver.cpp
nebula_ros/include/nebula_ros/common/diagnostics/severity_latch.hpp
nebula_ros/include/nebula_ros/hesai/diagnostics/functional_safety_diagnostic_task.hpp
nebula_ros/src/hesai/decoder_wrapper.cpp
nebula_tests/hesai/hesai_ros_decoder_test.cpp

- Bug Fix
In non-360 deg FoVs, Nebula was reporting the functional safety status as stuck. The reasons:
* outside the FoV, no packets are sent (e.g. 50 ms for 180 deg FoV), but Nebula expects FuSa to update every 5 ms
* reported error codes and stuck reports were aggregated together, with the more severe status winning
The solutions this PR implements are:
* to handle error code aggregation and stuck status aggregation separately
* allow up to 100ms until FuSa updates, instead of 5ms
<table>
<tr>
<th> Before </th>
<th> After </th>
</tr>
<tr>
<td>
[Screencast from 2025年08月08日 19時35分40秒.webm](https://github.com/user-attachments/assets/ca9d4d67-c328-46bb-9079-bfdc325f3a21)
</td>
<td>
[Screencast from 2025年08月08日 19時34分43秒.webm](https://github.com/user-attachments/assets/6592793d-998b-47b9-bd4 …

fix(hesai): fusa reports as stuck in non-360 deg FoVs

---

nebula_common/include/nebula_common/hesai/hesai_common.hpp

- Bug Fix
* https://github.com/tier4/nebula/issues/339
Based on my experience, the Hesai XT32 occasionally does not publish packets near the boundary of the FOV.
When that happens, Nebula cannot publish the point cloud at the correct timing. :cry: 
Currently, Nebula uses a calibration file downloaded to set the minimum FOV for the LiDAR, but this seems to be not sufficient. **Therefore, I added a fix that adjusts the FOV by ~~0.1~~ `1.0 degrees` .**
> [!NOTE]
> At least for all the “problematic” LiDARs I have encountered, this fix has been sufficient.
Here is a video of one of the “problematic” LiDARs I encountered.
https://github.com/user-attachments/assets/ef7b711b-031f-4551-858b-668d7660c1f3
When running nebula (v0.2.6.1), only a single line of point clouds is published.
However, if I …

fix(hesai_hw_interfaces): slightly widen FoV
